
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - VUE_APP_API_URL=http://localhost:8081
    

    
